(function(g){var window=this;var aza=function(a,b){var c=[];g.qi(b,function(a){try{var b=g.sD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.rD(b)&&c.push(a):c.push(a)},a);
return c},bza=function(a,b){var c=aza(a,b);
(0,g.G)(c,function(a){g.sD.prototype.remove.call(this,a)},a)},cza=function(){var a=g.aH;
bza(a,a.g.Vd(!0))},Q7=function(a,b){g.P0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.T=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},dza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},eza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},R7=function(){var a=dza();
a&&a(!1,"No cast extension found")},S7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},T7=function(a){if(a>=g.Ora.length)R7();
else{var b=g.Ora[a],c="chrome-extension://"+b+g.Lra;0<=g.k2.indexOf(b)?eza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,S7(c,R7)):T7(a+1)}):S7(c,function(){T7(a+1)})}},U7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},fza=function(){if(g.Mra){var a=2,b=dza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;S7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",R7,c)}},gza=function(){if(U7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){fza();a({command:"cast.sender.init"});return}}if(!window.chrome||U7("Edge"))R7();else if(fza(),U7("Android")&&U7("Chrome/")&&window.navigator.presentation){a="";var b=g.Kh();55<=b?a="55":50<=b&&(a="50");S7("//www.gstatic.com/eureka/clank"+a+g.Lra,R7)}else T7(0)},hza=function(a){g.tG[a]&&(a=g.tG[a],(0,g.G)(a,function(a){g.rG[a]&&delete g.rG[a]}),a.length=0)},iza=function(a){var b=g.qG();
if(b)if(b.clear(a),a)hza(a);else for(var c in g.tG)hza(c)},jza=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Cg(a)||"";b&&(this.port=":"+b);this.domain=g.Bg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Xa(a,"10.0")&&(this.o=!1))},kza=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},lza=function(){var a=window.document.createElement("a");
g.Vc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ya(a)},mza=function(a,b){var c=g.Ad("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Wc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},nza=function(){var a=lza(),b=window.document.getElementById(a),c=b&&g.GF(b,"loaded");
c||b&&!c||(b=mza(a,function(){g.GF(b,"loaded")||(g.FF(b,"loaded","true"),g.xG(a),g.IE(g.Ea(iza,a),0))}))},oza=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.hL||a},V7=function(a){g.qH("cloudview",a)},W7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},X7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},pza=function(a,b,c,d){var e=!1;
X7()||(a=new g.rI(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.cH("yt-remote-cast-available",a);g.yG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){V7("onReceiverSelected: "+a.friendlyName);
g.cH("yt-remote-cast-receiver",a);g.yG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){V7("onReceiverResumed: "+a.friendlyName);
g.cH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){V7("onSessionChange: "+g.yH(a));
a||g.eH("yt-remote-cast-receiver");g.yG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
V7("cloudview.createSingleton_: "+e);return e},qza=function(a){V7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},rza=function(){V7("dispose");
var a=X7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);qza(!1);g.vG(Y7);Y7.length=0},Z7=function(){return!!g.dH("yt-remote-cast-installed")},sza=function(){var a=g.dH("yt-remote-cast-receiver");
return a?a.friendlyName:null},tza=function(){V7("clearCurrentReceiver");
g.eH("yt-remote-cast-receiver")},$7=function(a){g.qH("cloudview",a)},uza=function(){return Z7()?X7()?X7().getCastSession():($7("getCastSelector: Cast is not initialized."),null):($7("getCastSelector: Cast API is not installed!"),null)},a8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},b8=function(){Z7()?X7()?a8()?(V7("Requesting cast selector."),X7().requestSession()):(V7("Wait for cast API to be ready to request the session."),Y7.push(g.uG("yt-remote-cast2-api-ready",b8))):$7("requestCastSelector: Cast is not initialized."):
$7("requestCastSelector: Cast API is not installed!")},c8=function(a,b){a8()?X7().setConnectedScreenStatus(a,b):$7("setConnectedScreenStatus called before ready.")},d8=function(a){V7("setCastInstalled_ "+a);
g.cH("yt-remote-cast-installed",a)},vza=function(a,b){X7().init(a,b)},wza=function(a,b){d8(!0);
W7(!1);vza(a,function(a){a?(qza(!0),g.xG("yt-remote-cast2-api-ready")):($7("Failed to initialize cast API."),d8(!1),g.eH("yt-remote-cast-available"),g.eH("yt-remote-cast-receiver"),rza());b(a)})},xza=function(a,b,c,d,e,f,k){oza()?pza(b,e,f,k)&&(W7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?wza(a,c):(window.__onGCastApiAvailable=function(b,d){b?wza(a,c):($7("Failed to load cast API: "+d),d8(!1),W7(!1),g.eH("yt-remote-cast-available"),g.eH("yt-remote-cast-receiver"),rza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):nza():gza())):V7("Cannot initialize because not running Chrome")},f8=function(a,b){g.hG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.GB;this.A=this.o=null;this.I=(0,g.z)(this.WN,this);this.F=(0,g.z)(this.ol,this);this.G=(0,g.z)(this.VN,this);this.J=(0,g.z)(this.jO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Au,this),yza(this))):c=3;0!=c&&(b?this.Au(c):g.IE((0,g.z)(function(){this.Au(c)},this),0));
var d=uza();d&&e8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},g8=function(a){return new g.xI(a.B.getPlayerContextData())},yza=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ea(this.nQ,a),this))},a)},zza=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},h8=function(a,b){50>a.C.Ic()&&g.IB(a.C,b)},j8=function(a,b,c){var d=g8(a);
g.AI(d,c);-1E3!=d.g&&(d.g=b);i8(a,d)},k8=function(a,b,c){a.B.sendMessage(b,c)},i8=function(a,b){zza(a);
a.B.setPlayerContextData(g.DI(b));yza(a)},e8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.ol(null));
a.A=b;a.A&&(l8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.ol(a.A.media[0]))},Aza=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=g8(a);b.contentId!=d.videoId&&l8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.AI(d,a.o.getEstimatedTime());i8(a,d)}else l8("No cast media video. Ignoring state update.")},l8=function(a){g.qH("CP",a)},m8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),k8(this,b,c))},a)},n8=function(a){g.DH.call(this,"ScreenServiceProxy");
this.bd=a;this.o=[];this.o.push(this.bd.$_s("screenChange",(0,g.z)(this.DT,this)));this.o.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.TP,this)))},o8=function(){return g.x("yt.mdx.remote.currentScreenId_")},p8=function(a){g.qH("remote",a)},q8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Bza=function(){var a=r8();
if(g.Vb(a)){a=g.JH();var b=g.dH("yt-remote-session-name")||"",c=g.dH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},Cza=function(a){a?(g.cH("yt-remote-session-app",a.app),g.cH("yt-remote-session-name",a.name)):(g.eH("yt-remote-session-app"),g.eH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},s8=function(){return g.x("yt.mdx.remote.connection_")},t8=function(){var a=s8();
return!!a&&3!=a.getProxyState()},Dza=function(){return g.x("yt.mdx.remote.connectData_")},v8=function(){if(!u8){var a=g.x("yt.mdx.remote.screenService_");
u8=a?new n8(a):null}return u8},w8=function(){var a=g.KH();
if(!a)return null;var b=v8().ee();return g.CH(b,a)},x8=function(){var a=o8();
if(!a)return null;var b=v8().ee();return g.CH(b,a)},Eza=function(){var a=v8().bd.$_gos();
var b=x8();b&&s8()&&(g.BH(a,b)||a.push(b));return kza(a)},Fza=function(){var a=Eza(),b=x8();
b||(b=w8());return g.eb(a,function(a){return b&&g.vH(b,a.key)?!0:!1})},y8=function(){var a=Fza();
!a&&Z7()&&sza()&&(a={key:"cast-selector-receiver",name:sza()});return a},Gza=function(){var a=Eza();
Z7()&&g.dH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Hza=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},A8=function(a){var b=s8();
q8(null);a||Hza("");g.ua("yt.mdx.remote.connection_",a,void 0);z8&&((0,g.G)(z8,function(b){b(a)}),z8.length=0);
b&&!a?g.yG("yt-remote-connection-change",!1):!b&&a&&g.yG("yt-remote-connection-change",!0)},C8=function(a,b){x8()&&x8();
Hza(a.id);var c=new g.JI(B8,a,r8());c.connect(b,Dza());c.subscribe("beforeDisconnect",function(a){g.yG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s8()&&A8(null)});
A8(c)},Iza=function(){var a=w8();
a?(p8("Resume connection to: "+g.yH(a)),C8(a,0)):(g.RH(),tza(),p8("Skipping connecting because no session screen found."))},D8=function(){a8()?X7().stopSession():$7("stopSession called before API ready.");
var a=s8();a&&(a.disconnect(1),A8(null))},Jza=function(a){p8("remote.onCastSessionChange_: "+g.yH(a));
if(a){var b=x8();b&&b.id==a.id?c8(b.id,"YouTube TV"):(b&&D8(),C8(a,1))}else s8()&&D8()},Kza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.$D("MDX_CONFIG")||b;g.aH&&cza();g.LH();B8||(B8=new jza(b?b.loungeApiHost:void 0),g.TH()&&(B8.g="/api/loungedev"));z8||(z8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",z8,void 0));Bza();var c=v8();if(!c){var d=new g.dI(B8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=v8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);xza(a,d,function(a){a?o8()&&c8(o8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.yG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),p8("Initializing: "+g.tg(b)),E8.push(g.uG("yt-remote-cast2-availability-change",function(){g.yG("yt-remote-receiver-availability-change")})),E8.push(g.uG("yt-remote-cast2-receiver-selected",function(){q8(null);
g.yG("yt-remote-auto-connect","cast-selector-receiver")})),E8.push(g.uG("yt-remote-cast2-receiver-resumed",function(){g.yG("yt-remote-receiver-resumed","cast-selector-receiver")})),E8.push(g.uG("yt-remote-cast2-session-change",Jza)),E8.push(g.uG("yt-remote-connection-change",function(a){a?c8(o8(),"YouTube TV"):w8()||(c8(null,null),tza())})),a=r8(),b.isAuto&&(a.id+="#dial"),g.nF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),p8(" -- with channel params: "+
g.tg(a)),Cza(a),c.start(),o8()||Iza())},F8=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.oc=b;this.C=(0,g.z)(this.qH,this);this.g=!1;this.o=0;this.A=this.za=null;this.B=[]},G8=function(a,b,c){g.L.call(this);
this.F=a;this.T=b;this.o=new g.eG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.mP);this.o.P(b,"captionschanged",this.UN);this.o.P(b,"captionssettingschanged",this.vC);this.o.P(b,"videoplayerreset",this.uo);this.o.P(b,"mdxautoplaycancel",this.yG);this.O=this.o.P(b,"onVolumeChange",this.NA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.aB,this);c.subscribe("remotePlayerChange",this.ql,this);c.subscribe("remoteQueueChange",this.uo,this);c.subscribe("autoplayUpNext",this.AA,
this);c.subscribe("previousNextChange",this.XA,this);c.subscribe("nowAutoplaying",this.PA,this);c.subscribe("autoplayDismissed",this.zA,this);this.suggestion=null;this.G=new g.MQ(64);this.A=new g.ut(this.qC,500,this);g.M(this,this.A);this.B=new g.ut(this.rC,1E3,this);g.M(this,this.B);this.J=new F8(this.cT,0,this);g.M(this,this.J);this.C={};this.L=new g.ut(this.TC,1E3,this);g.M(this,this.L);this.I=new g.mk(this.IK,1E3,this);g.M(this,this.I);this.N=g.y;this.vC();this.uo();this.ql()},H8=function(a,b){var c=
a.F,d=a.T.ga().lengthSeconds;
c.I=b||0;c.g.U("progresssync",b,d)},Lza=function(a){H8(a,0);
a.A.stop();I8(a,new g.MQ(64))},K8=function(a,b){if(J8(a)&&!a.D){var c=null;
b&&(c={style:a.T.li()},g.cc(c,b));a.g.jC(a.T.ga().videoId,c);a.C=g8(a.g).o}},L8=function(a,b){var c=a.T.Pf();
if(c){var d=c.ae();var e=c.listId.toString()}var f=a.T.ga();c=a.g;var k=a.T.ga().videoId,l=d;d=f.playerParams;f=f.oj;var m=g8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};g.CI(m,k,l);g.t(b)&&(g.AI(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);k8(c,"setPlaylist",q);e||i8(c,m);I8(a,new g.MQ(1))},Mza=function(a,b){if(b){var c=a.T.uc("captions","tracklist",{jy:1});
c&&c.length?(a.T.Cd("captions","track",b),a.D=!1):(a.T.al("captions"),a.D=!0)}else a.T.Cd("captions","track",{})},J8=function(a){return g8(a.g).videoId==a.T.ga().videoId},I8=function(a,b){a.B.stop();
var c=a.G;if(!g.RQ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.T;g.H1(e.app,d,e.playerType)}a.G=b;Nza(a.F,c,b)}},M8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.eE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.AX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);Oza(this,g.yW(a))},Oza=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.uc("remote","currentReceiver").name};
c=g.W(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.ib()||g.W(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},N8=function(a){g.sX.call(this,a);
this.A={key:g.AH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.MQ(64);this.I=0;var b=g.rW(a).G;b&&(b=b.A&&b.A.g)&&(b=new Q7(a,b),g.M(this,b));b=new M8(a);g.M(this,b);g.RW(a,b.element,4)},Nza=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.WQ(c,b))},O8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)D8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Pf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.fc(l).videoId}else k=[e];f=a.g.getCurrentTime();c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.oj,index:Math.max(a.g.rz(),0),currentTime:0==f?void 0:f}}else c=null;p8("Connecting to: "+g.tg(b));"cast-selector-receiver"==b.key?(q8(c||null),a8()?X7().setLaunchParams(c||null):$7("setLaunchParams called before ready.")):!c&&
t8()&&o8()==b.key?g.yG("yt-remote-connection-change",!0):(D8(),q8(c||null),c=v8().ee(),(c=g.CH(c,b.key))&&C8(c,1))}};
g.p(Q7,g.P0);Q7.prototype.I=function(){var a=this.T.uc("remote","receivers");a&&1<a.length&&!this.T.uc("remote","quickCast")?(this.F=g.Fb(a,this.B,this),g.Q0(this,(0,g.J)(a,this.B)),a=this.T.uc("remote","currentReceiver"),this.kf(this.B(a)),this.enable(!0)):this.enable(!1)};
Q7.prototype.B=function(a){return a.key};
Q7.prototype.jf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
Q7.prototype.pd=function(a){g.P0.prototype.pd.call(this,a);this.T.Cd("remote","currentReceiver",this.F[a]);this.A.Kb()};
g.h=jza.prototype;g.h.Vh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Lg(b+a,{})};
g.h.yu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Tb:g.Ea(this.yT,c,!0),onError:g.Ea(this.xT,d),Ed:g.Ea(this.zT,d)};b&&(c.Mb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.YE(a,c)};
g.h.yT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.xT=function(a,b){a(Error("Request error: "+b.status))};
g.h.zT=function(a){a(Error("request timed out"))};
var Y7=[];g.A(f8,g.hG);g.h=f8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,m8(this,"play")):k8(this,"play"),j8(this,1,g.BI(g8(this))),this.U("remotePlayerChange")):h8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,m8(this,"pause")):k8(this,"pause"),j8(this,2,g.BI(g8(this))),this.U("remotePlayerChange")):h8(this,this.pause)};
g.h.eD=function(a){if(1==this.g){if(this.o){var b=g8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ib()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,m8(this,"seekTo",{newTime:a}))}else k8(this,"seekTo",{newTime:a});j8(this,3,a);this.U("remotePlayerChange")}else h8(this,g.Ea(this.eD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,m8(this,"stopVideo")):k8(this,"stopVideo");var a=g8(this);a.index=-1;a.videoId="";g.yI(a);i8(this,a);this.U("remotePlayerChange")}else h8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=g8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){l8("set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){l8("set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);k8(this,"setVolume",e)}c.muted=b;c.volume=a;i8(this,c)}else h8(this,g.Ea(this.setVolume,a,b))};
g.h.jC=function(a,b){if(1==this.g){var c=g8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.tg(b.style),g.cc(d,c.o));k8(this,"setSubtitlesTrack",d);i8(this,c)}else h8(this,g.Ea(this.jC,a,b))};
g.h.zu=function(a,b){if(1==this.g){k8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qc.id});var c=g8(this);c.audioTrackId=b.Qc.id;i8(this,c)}else h8(this,g.Ea(this.zu,a,b))};
g.h.dD=function(a,b){if(1==this.g){if(a&&b){var c=g8(this);g.CI(c,a,b);i8(this,c)}k8(this,"previous")}else h8(this,g.Ea(this.dD,a,b))};
g.h.cD=function(a,b){if(1==this.g){if(a&&b){var c=g8(this);g.CI(c,a,b);i8(this,c)}k8(this,"next")}else h8(this,g.Ea(this.cD,a,b))};
g.h.Dw=function(){1==this.g?k8(this,"dismissAutoplay"):h8(this,this.Dw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}f8.Z.dispose.call(this)};
g.h.X=function(){zza(this);this.B=null;this.C.clear();e8(this,null);f8.Z.X.call(this)};
g.h.Au=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.JB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.nQ=function(a,b){this.U(a,b)};
g.h.WN=function(a){if(!a)this.ol(null),e8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=g8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)l8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,i8(this,b)}};
g.h.ol=function(a){l8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Aza(this),this.U("remotePlayerChange")};
g.h.VN=function(a){a?(Aza(this),this.U("remotePlayerChange")):this.ol(null)};
g.h.jO=function(){var a=uza();a&&e8(this,a)};
g.h.Zb=function(a){g.qH("CP",a)};
g.A(n8,g.DH);g.h=n8.prototype;g.h.ee=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.vp=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.ep=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.bd.$_ubk(this.o[a]);this.o.length=0;this.bd=null;n8.Z.X.call(this)};
g.h.DT=function(){this.U("screenChange")};
g.h.TP=function(){this.U("onlineScreenChange")};
var B8=null,z8=null,E8=[],u8=null;g.A(F8,g.L);g.h=F8.prototype;g.h.pH=function(a){this.B=arguments;this.g=!1;this.za?this.A=(0,g.F)()+this.oc:this.za=g.og(this.C,this.oc)};
g.h.stop=function(){this.za&&(g.pg(this.za),this.za=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.X=function(){this.stop();F8.Z.X.call(this)};
g.h.qH=function(){this.A?(this.za=g.og(this.C,this.A-(0,g.F)()),this.A=null):(this.za=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};g.p(G8,g.L);g.h=G8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.aB,this);this.g.unsubscribe("remotePlayerChange",this.ql,this);this.g.unsubscribe("remoteQueueChange",this.uo,this);this.g.unsubscribe("autoplayUpNext",this.AA,this);this.g.unsubscribe("previousNextChange",this.XA,this);this.g.unsubscribe("nowAutoplaying",this.PA,this);this.g.unsubscribe("autoplayDismissed",this.zA,this);this.g=this.F=null};
g.h.iz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(J8(this)){if(1081!=g8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":g8(this.g).ib()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.cj(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.g.zu(this.T.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.g.zu(this.T.ga().videoId,c)}};
g.h.UN=function(a){this.J.pH(a)};
g.h.cT=function(a){this.iz("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.vC=function(){var a=this.T.uc("captions","track");g.Vb(a)||K8(this,a)};
g.h.NA=function(a){if(J8(this)){this.g.unsubscribe("remotePlayerChange",this.ql,this);var b=Math.round(a.volume);a=!!a.muted;var c=g8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.ql,this)}};
g.h.mP=function(){g.Vb(this.C)||Mza(this,this.C);this.D=!1};
g.h.aB=function(a,b){this.B.stop();2==b&&this.rC()};
g.h.ql=function(){if(J8(this)){this.A.stop();var a=g8(this.g);switch(a.g){case 1081:I8(this,new g.MQ(8));break;case 1:this.qC();I8(this,new g.MQ(8));break;case 1083:case 3:I8(this,new g.MQ(9));break;case 0:I8(this,new g.MQ(2));this.I.stop();H8(this,this.T.ga().lengthSeconds);break;case 1082:I8(this,new g.MQ(4));break;case 2:I8(this,new g.MQ(4));H8(this,g.BI(a));break;case -1:I8(this,new g.MQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},I8(this,new g.MQ(128,
a))}a=g8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,Mza(this,a));a=g8(this.g);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.TC()}else Lza(this)};
g.h.XA=function(){this.T.U("mdxpreviousnextchange")};
g.h.uo=function(){J8(this)||Lza(this)};
g.h.yG=function(){this.g.Dw()};
g.h.AA=function(a){a&&(a=g.YE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},Tb:(0,g.z)(this.mR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.mR=function(a,b){var c=new g.OP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.U("mdxautoplayupnext",c)};
g.h.PA=function(a){(0,window.isNaN)(a)||this.T.U("mdxnowautoplaying",a)};
g.h.zA=function(){this.T.U("mdxautoplaycanceled")};
g.h.IK=function(a,b){-1==g8(this.g).g?L8(this,a):b&&this.g.eD(a)};
g.h.TC=function(){if(J8(this)){var a=g8(this.g);this.o.Da(this.O);a.muted?this.T.mute():this.T.Qf();this.T.setVolume(a.volume);this.O=this.o.P(this.T,"onVolumeChange",this.NA)}};
g.h.qC=function(){this.A.stop();if(!this.g.ka()){var a=g8(this.g);a.ib()&&I8(this,new g.MQ(8));H8(this,g.BI(a));this.A.start()}};
g.h.rC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(M8,g.Y);M8.prototype.B=function(a){Oza(this,a.state)};g.p(N8,g.sX);g.h=N8.prototype;g.h.create=function(){Kza(g.QN(g.X(this.g)));this.D.push(g.uG("yt-remote-before-disconnect",this.QN,this));this.D.push(g.uG("yt-remote-connection-change",this.wQ,this));this.D.push(g.uG("yt-remote-receiver-availability-change",this.YA,this));this.D.push(g.uG("yt-remote-auto-connect",this.uQ,this));this.D.push(g.uG("yt-remote-receiver-resumed",this.tQ,this));this.YA()};
g.h.load=function(){this.g.kq();g.sX.prototype.load.call(this);this.C=new G8(this,this.g,this.o);var a=Dza();a=a?a.currentTime:0;var b=t8()?new f8(s8(),void 0):null;0==a&&b&&(a=g.BI(g8(b)));0!=a&&(this.I=a||0,this.g.U("progresssync",a,void 0));Nza(this,this.F,this.F);g.L1(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.We(this.C,this.o);this.o=this.C=null;g.sX.prototype.unload.call(this);g.L1(this.g.app,5)};
g.h.X=function(){g.vG(this.D);g.sX.prototype.X.call(this)};
g.h.Uk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.iz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.lH=function(){return this.loaded?this.C.suggestion:null};
g.h.Ff=function(){return this.o?g8(this.o).Ff:!1};
g.h.hasNext=function(){return this.o?g8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.lK=function(){var a=g8(this.o),b=this.g.ga();return{allowSeeking:this.g.cd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+g.zI(a):a.B,isPeggedToLive:1>=(a.D?a.A+g.zI(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+g.zI(a):a.A,seekableStart:0<a.C?a.C+g.zI(a):a.C}};
g.h.mK=function(){this.o&&this.o.cD()};
g.h.nK=function(){this.o&&this.o.dD()};
g.h.QN=function(a){1==a&&(this.J=this.o?g8(this.o):null)};
g.h.wQ=function(){var a=t8()?new f8(s8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ve(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.pz(a.videoId,g.BI(a)));this.g.U("videodatachange","newdata",this.g.ga(),3)};
g.h.YA=function(){this.G=[this.A].concat(Gza());var a=y8()||this.A;O8(this,a);this.g.va("onMdxReceiversChange")};
g.h.uQ=function(){var a=y8();O8(this,a)};
g.h.tQ=function(){this.B=y8()};
g.h.kK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?b8():O8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&b8(),!0):!1}};
g.h.oK=function(){k8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.rd=function(){return!1};g.TZ.remote=N8;})(_yt_player);
